### ISSUE TITLE
отсутсвует библиотека

### ISSUE THREAD

**Issue by 4u4a64** [Awethon/open-api-python-client#1]
Я новичек и далеко не программер, но поему у вас ошибка 
Не могу найти библиотеку tinkoff-invest-openapi-client в https://pypi.org/simple/
setup.py у вас тоже  ссылается туда же, но её там нет

Installed /usr/local/lib/python3.6/dist-packages/tinkoff_invest_openapi_client-0.0.4-py3.6.egg
Processing dependencies for tinkoff-invest-openapi-client==0.0.4
Searching for websocket_client==0.56.0
Reading https://pypi.python.org/simple/websocket_client/
Download error on https://pypi.python.org/simple/websocket_client/: [Errno 111] Connection refused -- Some packages may not be found!
Reading https://pypi.python.org/simple/websocket-client/
Download error on https://pypi.python.org/simple/websocket-client/: [Errno 111] Connection refused -- Some packages may not be found!
Couldn't find index page for 'websocket_client' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 111] Connection refused -- Some packages may not be found!
No local packages or working download links found for websocket_client==0.56.0
error: Could not find suitable distribution for Requirement.parse('websocket_client==0.56.0')

**Comment by Awethon** [comment]
Здравствуйте, вы через ссылку в readme.md устанавливали?
Если перейти в pypi по ссылке https://pypi.python.org/simple/websocket-client/ то websocket_client нужной версии там пристутствует.
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/8236230/70276427-562ae480-17c1-11ea-82be-cd05beba5c4a.png">
выполнил установку с загрузкой всех библиотек
возможно провайдер блокирует индекс или он был временно недоступен
если ситуация не исправилась, можно попробовать подключиться через vpn и повторить установку

**Comment by Ipsilon91** [comment]
Здравствуйте,
у меня тупой вопрос. В примере дан вот такой метод для регистрации в песочнице `client.sandbox.sandbox_register_post()`
и с ним всё работает. А потом передаю уже боевой токен сюда
`client = openapi.api_client(token)`
а сам метод для регистрации клиента при использовании боевого токена найти не могу. При этом выдаётся ошибка, что проблемы с авторизацией
![Screenshot_2](https://user-images.githubusercontent.com/20323211/71119244-caff1500-21ea-11ea-9194-b17eadf37a95.png)

Помогите плиз.
