### ISSUE TITLE
Не работает market_order

### ISSUE THREAD

**Issue by Ruslan-Asadullin** [Awethon/open-api-python-client#11]
Здравствуйте! 
Пытаюсь запустить рыночный ордер:

```
def market_order(figi):
    order_response = client.orders.orders_market_order_post(figi,
                                                            market_order_request={"lots": 1,
                                                                                  "operation": "Buy"})
    return order_response
```

Но выполнение заканчивается ошибкой:
'OrdersApi' object has no attribute 'orders_market_order_post'

OrdersApi при этом содержит orders_market_order_post.
Подскажите, пожалуйста, где может быть проблема.
![20200323_223044](https://user-images.githubusercontent.com/57312893/77423289-f98b1e00-6ddf-11ea-932b-59ddb31399eb.jpg)
![IMG-20200323-WA0001](https://user-images.githubusercontent.com/57312893/77423312-027bef80-6de0-11ea-87eb-94eceda8a87b.jpeg)

**Comment by olli2017** [comment]
Проблема решена? У меня тоже это не сработало

**Comment by Ruslan-Asadullin** [comment]
> Проблема решена? У меня тоже это не сработало

Нет, но необходимости по идее и нет в выставлении ордеров по рынку, лучше пользоваться лимитным

**Comment by Alexxxandr99** [comment]
Решил так:

def make_order_market(figi, lots, operation):
    figi = figi
    lots = lots
    operation = operation
    order_response = client.orders.orders_market_order_post(figi=figi, async_req=True, market_order_request={"lots": lots, "operation": operation})
    print("make order market")
    print()
    return order_response
