### ISSUE TITLE
Не отображаются акции, полученные по акции

### ISSUE THREAD

**Issue by Ipsilon91** [Awethon/open-api-python-client#12]
Здравствуйте,
использую метод portfolio_get для получения позиций в портфеле, но не отображаются акции МТС, которые были получены по акции. Кроме них на счёте ещё доллары лежат, они верно отображаются.

**Comment by shapeless-space** [comment]
OpenApi не возвращает акционные инструменты из-за некоторых технических особенностей. Поддержку не планируем делать
