### ISSUE TITLE
Не могу купить акции ТКС

### ISSUE THREAD

**Issue by Ipsilon91** [Awethon/open-api-python-client#13]
Пытаюсь купить акции или депозитарные расписки ТКС, но выдаётся ошибка. Проверил trade_status, у него значение Not Available for trading. Это ошибка или так задумано? Хотелось бы всё-таки как-то их купить через API.

**Comment by Awethon** [comment]
Вроде бы сейчас вопросы по open api можно задавать прямо в чате инвестиций, к сожалению я не могу вам помочь с этой проблемой, я всего лишь разработчик библиотеки

**Comment by Ipsilon91** [comment]
ок, спасибо. Попробую написать туда
