### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED on streaming

### ISSUE THREAD

**Issue by scor2k** [Awethon/open-api-python-client#14]
При попытке подписаться на изменения по свечам (в sendbox) получаю шибку на сертификат:
```
from openapi_client.openapi_streaming import run_stream_consumer
from openapi_client.openapi_streaming import print_event

... 

candle_subs  = [
            {
                'figi': figi,
                'interval' : interval
            }
        ]
        
        run_stream_consumer(
            self.TOKEN,
            candle_subs,
            on_candle_event=print_event
        )
```

```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)
```

Не нашел в пакете отдельного URL для sandbox'а.
`
url = 'wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws'
`

Python 3.8.2 + MacOS Catalina 10.15.3 (19D76)

P.S. При работе с модулем на Go и таким же действием все работает без ошибок.
P.P.S. Python 3.6.8 + CentOS все работает без ошибок. На MacOS + 3.6.10 тоже все ок.

**Comment by Awethon** [comment]
Здравствуйте, по поводу сертификата ко мне уже обращались, к сожалению это редкий баг и сложно понять причины его происхождения.
url для websocket один, так как биржевые данные sandbox копируют настоящие

**Comment by siFon-kamikaza** [comment]
Нашел в интернете решение, которое лично мне помогло с такой же проблемой на маке. Суть мне не ясна, но нужно было в консоле дать команду:

open "/Applications/Python 3.7/Install Certificates.command"

Запускал прям в консоле PyCharm, не знаю важно ли это.

**Comment by AndyKruch** [comment]
open "/Applications/Python 3.7/Install Certificates.command" из предыдущего комментария помог, только запускать надо в терминале
