### ISSUE TITLE
Не подтягиваются данные по стоимости покупки позиции

### ISSUE THREAD

**Issue by Ipsilon91** [Awethon/open-api-python-client#15]
Здравствуйте.
Купил только что акции Детского мира (DSKY), запрашиваю данные о позиции через portfolio.portfolio_get() и он уже 10 мин не может посчитать стоимость позиции, которая выдаёт в payload.positions.[n].average_position_price значение None. Обычно так бывает секунд 5 после покупки, но сейчас как-то затянулся процесс. Не могли бы Вы посмотреть что случилось?
![DSKY none](https://user-images.githubusercontent.com/20323211/82803172-bbb28080-9e88-11ea-8f87-0c5b79ab73e1.png)

**Comment by Awethon** [comment]
Здравствуйте, библиотека лишь отправляет запросы в api и преобразует json в модель питона. Когда такое происходит, можно проверить, что это действительно на стороне api вызвав метод из https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/
(В Authorize нужно вставить свой токен, найти нужный метод, нажать Try it out, заполнить поля и затем нажать Execute)
И если проблема повторяется, то можно написать в чат приложения Тинькофф Инвестиций о проблеме, таким образом о ней узнают разработчики.
