### ISSUE TITLE
Функция operations_get()

### ISSUE THREAD

**Issue by Ruslan-Asadullin** [Awethon/open-api-python-client#16]
Добрый день!
При вызове функции operations_get() происходит API Exception (504), Gateway timeout.
Подскажите, пожалуйста, возможную причину и способ устранения ошибки. 
Информация по выполненным операциям крайне необходима.  
![ApiException](https://user-images.githubusercontent.com/57312893/84878684-d72d3780-b092-11ea-9aea-89c0c0353a36.png)

**Comment by Awethon** [comment]
Если api это возвращает, то скорее всего причина в именно в апи, попробуйте написать в чат Тинькофф Инвестиций

Можно проверить запрос через swagger https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/operations/get_operations
