### ISSUE TITLE
Ошибка при выставлении лимитного ордера

### ISSUE THREAD

**Issue by Ruslan-Asadullin** [Awethon/open-api-python-client#17]
Здравствуйте! При выставлении лимитного ордера через API происходит ошибка.
Запрос:
order_response = client.orders.order_limit_order_post
Ошибка:
openapi_genclient.exceptions.ApiException: (500). Reason: Internal Server Error

Подскажите, пожалуйста, как можно ее избежать в дальнейшем? Это сильно затрудняет использование API в автоматической торговле.
![20200807_114741](https://user-images.githubusercontent.com/57312893/89630985-cdf96380-d8a8-11ea-814f-e5d269eb54ba.jpg)

**Comment by codelooper75** [comment]
Руслан, я оставил свой вопрос по поводу API в issues в твоем репозитории, но ты его скрыл. Это мой телеграм, напиши пожалуйста "looper75"

**Comment by codelooper75** [comment]
> Здравствуйте! При выставлении лимитного ордера через API происходит ошибка.
> Запрос:
> order_response = client.orders.order_limit_order_post
> Ошибка:
> openapi_genclient.exceptions.ApiException: (500). Reason: Internal Server Error
> 
> Подскажите, пожалуйста, как можно ее избежать в дальнейшем? Это сильно затрудняет использование API в автоматической торговле.
> ![20200807_114741](https://user-images.githubusercontent.com/57312893/89630985-cdf96380-d8a8-11ea-814f-e5d269eb54ba.jpg)

Руслан, я оставил свой вопрос по поводу API в твоем репозитории, но ты его скрыл и переписка оборвалась. Это мой телеграм "looper75", напиши пожалуйста

**Comment by Ruslan-Asadullin** [comment]
Ответил вам в телеграмм

**Comment by Awethon** [comment]
Здравствуйте, это ведь ответ от сервера, к сожалению никак не избежать. Можно лишь поговорить с разработчиками API отправив им trackingId который в ответе есть, если это баг на их стороне, они пофиксят
