### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by codelooper75** [Awethon/open-api-python-client#18]
Здравствуйте! Подписался на стриминг одного инструмента, но не могу понять как получать данные в json например, а не просто вывести  принтом или писать в файл методом, объявленным прямо в файле openapi_streaming.py. 
`
....... 

candle_subs = [{'figi': 'BBG000C46HM9', 'interval': '1min'}]

run_stream_consumer(token,
                    candle_subs,
                    on_candle_event=to_candle_subscribe_json)
`

**Comment by Awethon** [comment]
Здравствуйте, необходимо просто соответствующим образом написать функцию to_candle_subscribe_json - она срабатывает каждый раз при получении ивента.

Что значит получать? События приходят постоянно, можно снаружи инициализировать список и в функции делать append или что-то подобное.

Было бы проще, если бы вы описали то, что хотите в конечном итоге сделать.

**Comment by igor-i-plotnikov** [comment]
@Awethon 

> необходимо просто соответствующим образом написать функцию to_candle_subscribe_json

видимо, вы имели в виду функцию on_candle_event?
не подскажете, как лучше всего отдавать вовне полученный ивент? не могу сообразить
