### ISSUE TITLE
portfolio_get() и переключение между типами счетов

### ISSUE THREAD

**Issue by zloysnegovik** [Awethon/open-api-python-client#19]
Добрый день!))

Если в тинькове открыто два счёта (брокерский и ИИС), то функция portfolio_get() по умолчанию подключается к брокерскому.
В библиотеке функция объявляется так
`def portfolio_get(self, **kwargs):`
и, по логике, должна принимать парметры. Но, когда я пытаюсь передать параметр, возвращает такую ошибку
`TypeError: portfolio_get() takes 1 positional argument but 2 were given`

В классе BrokerAccountType я нашёл такие значения
`TINKOFF = "Tinkoff"`
`TINKOFFIIS = "TinkoffIis"`

Как мне корректно вызвать функцию portfolio_get() чтобы получить данные с иис, а не с брокерского счёта?

**Comment by gitnull** [comment]
Там надо указывать в формате
client.portfolio.portfolio_get(broker_account_id='2001234567')

Номер своего счета ИИС можно посмотреть, например, в брокерском отчете в pdf в самом верху

**Comment by zloysnegovik** [comment]
Спасибо, помогло))

**Comment by zloysnegovik** [comment]
Спасибо, помогло))
