### ISSUE TITLE
Не запускается streaming из examples

### ISSUE THREAD

**Issue by Strofimov07** [Awethon/open-api-python-client#2]
Привет! Подскажи, пожалуйста, при попытке запустить стриминг из примеров с боевым токеном, возникает ошибка [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)

Что-то не так с установкой было или в чем причина?

**Comment by Awethon** [comment]
Здравствуйте, скорее всего с установкой у вас всё хорошо.
Если перейти в браузере по ссылке https://api-invest.tinkoff.ru/openapi/sandbox/register и кликнуть на замочек, можно увидеть сертификат и что он не самоподписанный.
![image](https://user-images.githubusercontent.com/8236230/70698721-19874d80-1cd9-11ea-8d09-747206e7e9d3.png)

Провайдеры могут подменять SSL сертификат. Попробуйте повторить запуск через другого провайдера либо подключив VPN.

Статьи об этом:
https://habr.com/ru/post/303736/
https://habr.com/ru/sandbox/88671/
https://toster.ru/q/394759

**Comment by Strofimov07** [comment]
Спасибо!

**Comment by daragok** [comment]
@Strofimov07 у вас решилась проблема с certificate verify failed: self signed certificate in certificate chain? 
Мне не помогли смена провайдера и использование VPN

**Comment by Strofimov07** [comment]
@daragok Получилось только запустив на виртуальной машине
