### ISSUE TITLE
Отписка от событий streaming

### ISSUE THREAD

**Issue by gitnull** [Awethon/open-api-python-client#20]
Здравствуйте!
Непонятно как отписываться от событий (свечи, инструменты), которые стали не актуальны.
Или как хотя бы остановить run_stream_consumer и перезапустить его?

**Comment by Awethon** [comment]
к сожалению такое я решил в библиотеке не поддерживать, это сильно усложнит и код и процесс взаимодействия, посмотрите другие библиотеки на предмет такой функциональности

**Comment by gitnull** [comment]
Жаль. Буду переписывать с библиотекой Fatal1ty
