### ISSUE TITLE
Значение 'time' в [payload][candles]

### ISSUE THREAD

**Issue by KirillLem** [Awethon/open-api-python-client#25]
**Приветствую!** 

**При запросе исторических данных приходит ответ, где поле 'time' имеет вид datetime.datetime(2020, 12, 4, 7, 30, tzinfo=tzutc()), это не позволяет распарсить результат с помощью модуля json. Причем в  swagger это не вопроизводится.
Подскажите, пожалуйста, в чем может быть проблема?**

inst_figi = BBG000B9XRY4
d1 = timezone('Europe/Moscow').localize(datetime(2020, 12, 4, 10, 0, 0), is_dst=None)
d2 = timezone('Europe/Moscow').localize(datetime(2020, 12, 4, 11, 0, 0), is_dst=None)
candles = client.market.market_candles_get(figi = inst_figi, _from=d1.isoformat(), to=d2.isoformat(), interval='30min')
print(candles)

**Результат:**

{'payload': {'candles': [{'c': 50.47,
                          'figi': 'BBG00TCBG714',
                          'h': 50.58,
                          'interval': '30min',
                          'l': 50.0,
                          'o': 50.58,
                          'time': datetime.datetime(2020, 12, 4, 7, 0, tzinfo=tzutc()),
                          'v': 298},
                         {'c': 50.45,
                          'figi': 'BBG00TCBG714',
                          'h': 50.5,
                          'interval': '30min',
                          'l': 50.45,
                          'o': 50.48,
                          'time': datetime.datetime(2020, 12, 4, 7, 30, tzinfo=tzutc()),
                          'v': 108}],
             'figi': 'BBG00TCBG714',
             'interval': '30min'},
 'status': 'Ok',
 'tracking_id': '748b00cac578d1ae'}

**Comment by mikhashev** [comment]
Попробуйте получать значения таким способом:

for candle in candles.payload.candles:

    price_open = candle.o
    price_high = candle.h
    price_low = candle.l
    price_close = candle.c
    time_data = candle.time
    volume = candle.v
    print(price_open)
