### ISSUE TITLE
неверно отрабатывает запрос свечей с интервалом 15 минут

### ISSUE THREAD

**Issue by daragok** [Awethon/open-api-python-client#3]
отправляю запрос в sandbox
```
figi = 'BBG000B9XRY4'
date = 2019-12-13 22:30:00+00:00
to_date = 2019-12-13 23:00:00+00:00
interval = '15min'
client.market.market_candles_get(figi, date, to_date, interval)
```
в ответе получаю одну свечу (от 22:30 до 22:45), хотя должно быть две 
Терминал Тинькофф инвестиций две показывает, 
с 22:30 до 22:45 и с 22:45 до 23:00

**Comment by Awethon** [comment]
Если проблема воспроизводится в swagger, то пишите лучше на openapi_invest@tinkoff.ru
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles
2019-12-13 22:30:00+00:00 - это время UTC, московское время в этот момент на три часа больше.

2019-12-13 22:30:00+03:00 -  если хотите передать московское, то писать надо вот так

**Comment by daragok** [comment]
да, в сваггере воспроизводится, спасибо 
напишу на почту в тинькофф 

время в UTC ставил умышленно для унификации, спасибо
