### ISSUE TITLE
Помогите запустить боевую версию

### ISSUE THREAD

**Issue by Ipsilon91** [Awethon/open-api-python-client#4]
Здравствуйте,
у меня тупой вопрос. В примере дан вот такой метод для регистрации в песочнице `client.sandbox.sandbox_register_post()`
и с ним всё работает. А потом передаю уже боевой токен сюда
`client = openapi.api_client(token)`
а сам метод для регистрации клиента при использовании боевого токена найти не могу. При этом выдаётся ошибка, что проблемы с авторизацией
![Screenshot_2](https://user-images.githubusercontent.com/20323211/71326510-019b9f00-250d-11ea-8366-33b8b517fa3d.png)

Помогите плиз

**Comment by shapeless-space** [comment]
Токен для сендбокса не подходит для бирживой торговли.
Возможно вы не поменяли его?

**Comment by Ipsilon91** [comment]
> Токен для сендбокса не подходит для бирживой торговли.
> Возможно вы не поменяли его?

Проверил. Токен поменял на боевой.

**Comment by shapeless-space** [comment]
Ошибка все еще воспроизводится?

**Comment by Ipsilon91** [comment]
Да, ошибка была. На всякий случай решил получить новый боевой токен, после этого заработало. Теперь всё хорошо. Спасибо)
