### ISSUE TITLE
Исключение в market_search_by_ticker_get

### ISSUE THREAD

**Issue by dmitrySorokin** [Awethon/open-api-python-client#7]
client.market.market_search_by_ticker_get('AAPL')
Бросает исключение:
ValueError: Invalid value for `figi`, must not be `None`

**Comment by dmitrySorokin** [comment]
Проблема возникает в api_client.__deserialize_model
В data возвращается вот такой словарь: 
{'instruments': [{'figi': 'BBG000B9XRY4', 'ticker': 'AAPL', 'isin': 'US0378331005', 'minPriceIncrement': 0.01, 'lot': 1, 'currency': 'USD', 'name': 'Apple', 'type': 'Stock'}], 'total': 1}

Код написан так, что он ждет словарь вида: 
{'figi': 'BBG000B9XRY4', 'ticker': 'AAPL', 'isin': 'US0378331005', 'minPriceIncrement': 0.01, 'lot': 1, 'currency': 'USD', 'name': 'Apple', 'type': 'Stock'}

**Comment by Awethon** [comment]
Попробуйте обновить библиотеку:
pip3 install -i https://test.pypi.org/simple/ tinkoff-invest-openapi-client

В седьмой версии всё должно быть ок

**Comment by konstunn** [comment]
Подтверждаю проблему в шестой версии. Подтверждаю, что в седьмой версии исправлено. А еще to_dict() работает намного быстрее. Спасибо!

**Comment by dmitrySorokin** [comment]
В 7 версии работает. Спасибо!
