### ISSUE TITLE
Are rate limits taken into account somehow?

### ISSUE THREAD

**Issue by konstunn** [Awethon/open-api-python-client#8]
Hi. 

Does this SDK take care of rate limits somehow? 

I mean may be it could at first make a HEAD request, look at the x-rate-lim* headers and make a decision whether to make a request with payload or take a timeout, raise corresponding exception, and so on.

**Comment by Awethon** [comment]
Checking rate limits for every request to api might affect performance of trading bots.
I don't think it would be a useful feature to have since the most common use case is to listen to candle events and make requests to api on some condition.
